export const SAMPLE_PROBLEMS = [
  {
    id: "1",
    title: "Pothole Crisis on Kissy Street, Freetown",
    description:
      "Multiple large potholes damaging vehicles daily. The main road is deteriorating rapidly and poses a safety hazard to commuters.",
    category: "roads",
    categoryLabel: "Roads & Potholes",
    location: "Kissy Street, Freetown",
    upvotes: 456,
    status: "in-progress",
    thumbnail: "/pothole-road-damage.jpg",
    reportedBy: "Amara Sesay",
    reportedDate: "2025-01-18",
    hasUpvoted: false,
    severity: 92,
    coordinates: { lat: 50, lng: -70 },
  },
  {
    id: "2",
    title: "Water Supply Shortage in Bo District",
    description:
      "Residents have had no water supply for over a week. The main pipeline has ruptured and needs urgent repair.",
    category: "water",
    categoryLabel: "Water Supply",
    location: "Bo District Center",
    upvotes: 342,
    status: "pending",
    thumbnail: "/water-pipe-infrastructure.jpg",
    reportedBy: "Ibrahim Koroma",
    reportedDate: "2025-01-19",
    hasUpvoted: false,
    severity: 95,
    coordinates: { lat: 35, lng: -50 },
  },
  {
    id: "3",
    title: "Non-Functional Street Lights in Makeni",
    description:
      "Over 50% of street lights in central Makeni are not working. This is a major safety concern, especially at night.",
    category: "electricity",
    categoryLabel: "Electricity",
    location: "Makeni City Center",
    upvotes: 289,
    status: "in-progress",
    thumbnail: "/broken-street-light-night.jpg",
    reportedBy: "Fatima Bah",
    reportedDate: "2025-01-17",
    hasUpvoted: false,
    severity: 88,
    coordinates: { lat: 60, lng: -45 },
  },
  {
    id: "4",
    title: "Waste Management Crisis in Kenema Market",
    description:
      "Overflowing garbage bins creating a public health hazard. The waste collection schedule is not being followed.",
    category: "waste",
    categoryLabel: "Waste Management",
    location: "Kenema Central Market",
    upvotes: 278,
    status: "pending",
    thumbnail: "/garbage-waste-bins.jpg",
    reportedBy: "Mohamed Jalloh",
    reportedDate: "2025-01-20",
    hasUpvoted: false,
    severity: 85,
    coordinates: { lat: 25, lng: -55 },
  },
  {
    id: "5",
    title: "Dangerous Intersection at Kono Junction",
    description:
      "Multiple traffic accidents reported. The intersection needs traffic signals and improved road markings urgently.",
    category: "safety",
    categoryLabel: "Public Safety",
    location: "Kono Junction",
    upvotes: 534,
    status: "pending",
    thumbnail: "/busy-intersection-traffic.jpg",
    reportedBy: "Sekou Bangura",
    reportedDate: "2025-01-15",
    hasUpvoted: false,
    severity: 94,
    coordinates: { lat: 40, lng: -35 },
  },
  {
    id: "6",
    title: "Flooded Roads During Rainy Season in Port Loko",
    description:
      "Poor drainage system causing severe flooding on major roads. Vehicles cannot pass and residents are stranded.",
    category: "roads",
    categoryLabel: "Roads & Potholes",
    location: "Port Loko Town Center",
    upvotes: 201,
    status: "in-progress",
    thumbnail: "/pothole-road-damage.jpg",
    reportedBy: "Isha Conteh",
    reportedDate: "2025-01-16",
    hasUpvoted: false,
    severity: 87,
    coordinates: { lat: 55, lng: -60 },
  },
  {
    id: "7",
    title: "Water Pipeline Leakage in Lunsar",
    description:
      "Major water loss due to leaking pipes. The water company needs to conduct urgent maintenance and repairs.",
    category: "water",
    categoryLabel: "Water Supply",
    location: "Lunsar Town",
    upvotes: 165,
    status: "resolved",
    thumbnail: "/water-pipe-infrastructure.jpg",
    reportedBy: "Rashid Kamara",
    reportedDate: "2025-01-10",
    hasUpvoted: false,
    severity: 78,
    coordinates: { lat: 45, lng: -65 },
  },
  {
    id: "8",
    title: "Power Outages in Waterloo Suburb",
    description: "Frequent and prolonged power cuts affecting residents' daily activities. Power supply is unstable.",
    category: "electricity",
    categoryLabel: "Electricity",
    location: "Waterloo Suburb, Freetown",
    upvotes: 312,
    status: "in-progress",
    thumbnail: "/broken-street-light-night.jpg",
    reportedBy: "Zainab Diallo",
    reportedDate: "2025-01-19",
    hasUpvoted: false,
    severity: 81,
    coordinates: { lat: 42, lng: -75 },
  },
  {
    id: "9",
    title: "Abandoned Waste in Magburaka",
    description: "Illegal dumping of medical and industrial waste. Environmental hazard affecting the local community.",
    category: "waste",
    categoryLabel: "Waste Management",
    location: "Magburaka Outskirts",
    upvotes: 198,
    status: "pending",
    thumbnail: "/garbage-waste-bins.jpg",
    reportedBy: "Peter Sesay",
    reportedDate: "2025-01-20",
    hasUpvoted: false,
    severity: 89,
    coordinates: { lat: 65, lng: -40 },
  },
  {
    id: "10",
    title: "School Area Safety - Missing Road Signs in Hastings",
    description: "Missing warning signs near schools causing accidents. Children are at risk during school hours.",
    category: "safety",
    categoryLabel: "Public Safety",
    location: "Hastings School Zone, Freetown",
    upvotes: 423,
    status: "resolved",
    thumbnail: "/busy-intersection-traffic.jpg",
    reportedBy: "Marie Turay",
    reportedDate: "2025-01-05",
    hasUpvoted: false,
    severity: 90,
    coordinates: { lat: 38, lng: -72 },
  },
  {
    id: "11",
    title: "Bridge Deterioration on Aberdeen-Lumpa Road",
    description:
      "The historic bridge shows severe structural damage. Engineers have warned it may be unsafe for vehicles.",
    category: "roads",
    categoryLabel: "Roads & Potholes",
    location: "Aberdeen-Lumpa Road",
    upvotes: 567,
    status: "pending",
    thumbnail: "/pothole-road-damage.jpg",
    reportedBy: "Joseph Kamara",
    reportedDate: "2025-01-14",
    hasUpvoted: false,
    severity: 96,
    coordinates: { lat: 48, lng: -68 },
  },
  {
    id: "12",
    title: "Contaminated Water Supply in Kamara",
    description:
      "Local well water is contaminated with harmful bacteria. Health officials recommend boiling water urgently.",
    category: "water",
    categoryLabel: "Water Supply",
    location: "Kamara Village",
    upvotes: 289,
    status: "pending",
    thumbnail: "/water-pipe-infrastructure.jpg",
    reportedBy: "Miriam Bangura",
    reportedDate: "2025-01-18",
    hasUpvoted: false,
    severity: 93,
    coordinates: { lat: 30, lng: -80 },
  },
  {
    id: "13",
    title: "Illegal Dumping Site Near Bathurst",
    description: "A large illegal dumping site has emerged near Bathurst causing environmental and health concerns.",
    category: "waste",
    categoryLabel: "Waste Management",
    location: "Near Bathurst, Eastern Region",
    upvotes: 234,
    status: "in-progress",
    thumbnail: "/garbage-waste-bins.jpg",
    reportedBy: "Ahmed Carew",
    reportedDate: "2025-01-17",
    hasUpvoted: false,
    severity: 84,
    coordinates: { lat: 20, lng: -45 },
  },
  {
    id: "14",
    title: "Traffic Safety Issues at Lumley Beach Road",
    description:
      "High-speed vehicles, pedestrians, and cyclists share the same road without proper separation. Multiple injuries reported.",
    category: "safety",
    categoryLabel: "Public Safety",
    location: "Lumley Beach Road, Freetown",
    upvotes: 398,
    status: "in-progress",
    thumbnail: "/busy-intersection-traffic.jpg",
    reportedBy: "Kemu Jalloh",
    reportedDate: "2025-01-19",
    hasUpvoted: false,
    severity: 86,
    coordinates: { lat: 52, lng: -72 },
  },
]

export const getCategoryColor = (category: string) => {
  const colors: Record<string, string> = {
    water: "bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-400",
    waste: "bg-amber-100 text-amber-800 dark:bg-amber-900/20 dark:text-amber-400",
    roads: "bg-slate-100 text-slate-800 dark:bg-slate-900/20 dark:text-slate-400",
    electricity: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-400",
    safety: "bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-400",
  }
  return colors[category] || colors.roads
}

export const getStatusBadge = (status: string) => {
  const badges: Record<string, { label: string; color: string }> = {
    pending: { label: "Pending", color: "bg-gray-100 text-gray-800 dark:bg-gray-900/20 dark:text-gray-400" },
    "in-progress": { label: "In Progress", color: "bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-400" },
    resolved: { label: "Resolved", color: "bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400" },
  }
  return badges[status] || badges.pending
}

export const getSeverityColor = (severity: number) => {
  if (severity >= 90) return "text-red-600 bg-red-50 dark:text-red-400 dark:bg-red-950/20"
  if (severity >= 80) return "text-orange-600 bg-orange-50 dark:text-orange-400 dark:bg-orange-950/20"
  if (severity >= 70) return "text-yellow-600 bg-yellow-50 dark:text-yellow-400 dark:bg-yellow-950/20"
  return "text-green-600 bg-green-50 dark:text-green-400 dark:bg-green-950/20"
}

export const getCategoryIcon = (category: string) => {
  const icons: Record<string, string> = {
    water: "💧",
    waste: "🗑️",
    roads: "🛣️",
    electricity: "⚡",
    safety: "🚨",
  }
  return icons[category] || "📍"
}
